name: Deploy Backend to Ubuntu Server

on:
  push:
    branches:
      - main
    paths:
      - "backend/demo/**" # Solo ejecutar si hay cambios en el backend

jobs:
  deploy:
    # Usamos el runner local que instalarás en tu servidor (/home/user24)
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven
        working-directory: ./backend/demo
        run: ./mvnw clean package -DskipTests

      - name: Restart Systemd Service
        # Reinicia el servicio usando sudo (deberemos darle permisos sin contraseña a user24 para este comando)
        run: sudo systemctl restart legalyze-backend
